### ISSUE TITLE
Use Jest for testing

### ISSUE THREAD

**Issue by RubenVerborgh** [inrupt/wac-ldp#10]
I strongly recommend using Jest for testing. Mocha isn't really _the_ thing anymore, and Jest has great support for parallelization and mocking.

**Comment by michielbdejong** [comment]
ok, will have a look and discuss with @jaxoncreed ! One thing i don't like about mocha is https://remarkablemark.org/blog/2016/08/20/arrow-functions-in-mocha/

**Comment by dsebastien** [comment]
+1 for Jest

**Comment by jaxoncreed** [comment]
I don't have a strong opinion on Jest vs Mocha. Though from what I've heard, the big benefit for using Jest is that you don't have to do as much configuration as Mocha. Given the configuration for Mocha is already done in this project, that seems to be a moot point.

**Comment by dsebastien** [comment]
One advantage that I see with Jest is that it has a large feature-set out of the box and support for advanced features (aync testing, mocks, timers) without the need for third-party libraries.

Jest has built-in support for code coverage reporting too.

**Comment by michielbdejong** [comment]
ok, i'll try it out. since there are only 10 tests so far, switching now will be easier than switching later :)
