### ISSUE TITLE
error in build wac-ldp@0.9.1

### ISSUE THREAD

**Issue by bourgeoa** [inrupt/wac-ldp#166]
It relates to filenames not coherent (upper/lower case letter) 
- between `src/lib/core/DefaultOperationFactory.ts` and `src/lib/operationHandlers/containerMemberAddHandler.ts`
- with `src/lib/core/operationHandlers/` 

Is there a reason why some files begin with a Uppercase letter and other not ?

> > wac-ldp@0.9.1 build /pod-server/node_modules/wac-ldp
> tsc -p tsconfig.json
>
> src/lib/core/DefaultOperationFactory.ts(3,32): error TS2307: Cannot find module '../operationHandlers/OptionsHandler'.
src/lib/core/DefaultOperationFactory.ts(4,33): error TS2307: Cannot find module '../operationHandlers/GlobReadHandler'.
src/lib/core/DefaultOperationFactory.ts(5,43): error TS2307: Cannot find module '../operationHandlers/ContainerMemberAddHandler'.
src/lib/core/DefaultOperationFactory.ts(6,38): error TS2307: Cannot find module '../operationHandlers/ReadContainerHandler'.
src/lib/core/DefaultOperationFactory.ts(7,40): error TS2307: Cannot find module '../operationHandlers/DeleteContainerHandler'.
src/lib/core/DefaultOperationFactory.ts(8,33): error TS2307: Cannot find module '../operationHandlers/ReadBlobHandler'.
src/lib/core/DefaultOperationFactory.ts(9,34): error TS2307: Cannot find module '../operationHandlers/WriteBlobHandler'.
src/lib/core/DefaultOperationFactory.ts(10,35): error TS2307: Cannot find module '../operationHandlers/UpdateBlobHandler'.
src/lib/core/DefaultOperationFactory.ts(11,35): error TS2307: Cannot find module '../operationHandlers/DeleteBlobHandler'.
src/lib/core/DefaultOperationFactory.ts(12,42): error TS2307: Cannot find module '../operationHandlers/UnknownOperationCatchAll'.
src/lib/operationHandlers/containerMemberAddHandler.ts(10,34): error TS2307: Cannot find module './WriteBlobHandler'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! wac-ldp@0.9.1 build: `tsc -p tsconfig.json`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the wac-ldp@0.9.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by michielbdejong** [comment]
Thanks for reporting! Just ran into this as well myself, will fix now.

**Comment by michielbdejong** [comment]
I think this should be fixed in 0.9.4 now.
