### ISSUE TITLE
Introduce GreenKeeper to automate dependency updates

### ISSUE THREAD

**Issue by dsebastien** [inrupt/wac-ldp#19]
https://greenkeeper.io/

Goal: automatically get pull requests for dependencies that aren't up to date. That way we can freeze versions, avoid surprises but still easily update things in a controlled manner.

If Travis executes the test suite on PRs (cfr #17), then we have an idea of the impact on the test suite, and we can easily evaluate (one by one) what has changed in the dependency that could impact us.

**Comment by michielbdejong** [comment]
done
