### ISSUE TITLE
Add Memento support for resource versioning

### ISSUE THREAD

**Issue by pmcb55** [inrupt/wac-ldp#32]
Feature request to add Memento (https://tools.ietf.org/html/rfc7089) support to allow resource versioning.

This feature would effectively mark resources as immutable, as each atomic change (i.e. possibly multiple changes to a resource, but all taking place within a single atomic transaction) will be recorded as a timestamped version of that resource. Would allow a user to retrieve previous versions of any resource.

Feature could be marked (using the resource meta-data) as optional per resource (e.g. if disk space was a concern).

**Comment by dsebastien** [comment]
Hi @pmcb55. Great proposal. The temporal aspect of the resources is clearly of interest.

I'd like to again make the link with https://github.com/solid/user-stories/issues/22. If we are to integrate Memento on top of Solid's data store, then of course the whole history of the underlying data needs to be maintained (at least for those resources that we wish to expose with an history).

Again I think that an event-driven architecture and event sourcing in particular would enable this (among other benefits).

**Comment by michielbdejong** [comment]
We'll wait to see if this gets added in the 1.0 spec, until then the 0.8 spec acts as our PRD.
