### ISSUE TITLE
Feature request to support LDN

### ISSUE THREAD

**Issue by pmcb55** [inrupt/wac-ldp#33]
Just a placeholder for Linked Data Notification support - LDP support already implies a degree of LDN support (i.e. to be an LDN 'receiver'), but provider 'sender' support would be useful to allow notifications to be sent from a POD based on application triggers (e.g. a new photo being uploaded sending a notification to family members).

**Comment by michielbdejong** [comment]
Thanks! Good point. The current spec is not explicit about which parts of LDN it includes as required and which ones are optional, but https://github.com/solid/solid-platform#servers does list WSS and not outgoing webhooks, so we could interpret that as such. I think we should first clarify the spec stating that version 0.7 only includes WebSockets, and then we can propose adding outgoing webhooks as a possible feature in version 0.8. One question we would have to answer is how you would tell your pod to add/remove such a webhook? Or are you thinking these webhooks should only be added and used by the pod provider and not by the end user? The example with the photo / family member suggests that you want this as a feature at the end-user level, right?

**Comment by michielbdejong** [comment]
We'll wait to see if this gets added in the 1.0 spec, until then the 0.8 spec acts as our PRD.
