### ISSUE TITLE
Support JSON-LD ACL docs

### ISSUE THREAD

**Issue by michielbdejong** [inrupt/wac-ldp#45]

**Comment by michielbdejong** [comment]
Blocked by https://github.com/solid/web-access-control-spec/issues/45 but it may work if i use rdflib.js instead of rdf-ext.

**Comment by elf-pavlik** [comment]
Most applications don't have to fetch the vocab, could you please share example of you ACL in JSON-LD? I would like to take a look at your `@context` if you use compacted JSON-LD.

**Comment by michielbdejong** [comment]
This is what I was testing with:
```json
{
  "@context": "http://www.w3.org/ns/auth/acl#",
  "@type": "http://www.w3.org/ns/auth/acl#Authorization",
  "agent": [
    "https://michielbdejong.inrupt.net/profile/card#me",
    "mailto:michiel@unhosted.org"
  ],
  "accessTo": "/",
  "default": "/",
  "mode": [
    "http://www.w3.org/ns/auth/acl#Read",
    "http://www.w3.org/ns/auth/acl#Write",
    "http://www.w3.org/ns/auth/acl#Control"
  ]
}
```

**Comment by elf-pavlik** [comment]
Please try

```jsonld
{
  "@context": {
    "wac": "http://www.w3.org/ns/auth/acl#",
    "agent": {"@id": "wac:agent", "@type": "@id"},
    "accessTo": {"@id": "wac:accessTo"},
    "default": {"@id": "wac:default"},
    "mode": {"@id": "wac:mode", "@type": "@vocab"},
    "Read": {"@id": "wac:Read"},
    "Write": {"@id": "wac:Write"},
    "Control": {"@id": "wac:Control"}
  },
  "@type": "http://www.w3.org/ns/auth/acl#Authorization",
  "agent": [
    "https://michielbdejong.inrupt.net/profile/card#me",
    "mailto:michiel@unhosted.org"
  ],
  "accessTo": "/",
  "default": "/",
  "mode": [
    "Read",
    "Write",
    "Control"
  ]
}
```

[see N-Triples in JSON-LD playground](https://json-ld.org/playground/#startTab=tab-nquads&json-ld=%7B%22%40context%22%3A%7B%22wac%22%3A%22http%3A%2F%2Fwww.w3.org%2Fns%2Fauth%2Facl%23%22%2C%22agent%22%3A%7B%22%40id%22%3A%22wac%3Aagent%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22accessTo%22%3A%7B%22%40id%22%3A%22wac%3AaccessTo%22%7D%2C%22default%22%3A%7B%22%40id%22%3A%22wac%3Adefault%22%7D%2C%22mode%22%3A%7B%22%40id%22%3A%22wac%3Amode%22%2C%22%40type%22%3A%22%40vocab%22%7D%2C%22Read%22%3A%7B%22%40id%22%3A%22wac%3ARead%22%7D%2C%22Write%22%3A%7B%22%40id%22%3A%22wac%3AWrite%22%7D%2C%22Control%22%3A%7B%22%40id%22%3A%22wac%3AControl%22%7D%7D%2C%22%40type%22%3A%22http%3A%2F%2Fwww.w3.org%2Fns%2Fauth%2Facl%23Authorization%22%2C%22agent%22%3A%5B%22https%3A%2F%2Fmichielbdejong.inrupt.net%2Fprofile%2Fcard%23me%22%2C%22mailto%3Amichiel%40unhosted.org%22%5D%2C%22accessTo%22%3A%22%2F%22%2C%22default%22%3A%22%2F%22%2C%22mode%22%3A%5B%22Read%22%2C%22Write%22%2C%22Control%22%5D%7D)
