### ISSUE TITLE
Why is mergeRdfSources.ts so hard-coded?

### ISSUE THREAD

**Issue by pmcb55** [inrupt/wac-ldp#52]
In this source (https://github.com/inrupt/wac-ldp/blob/master/src/lib/util/mergeRdfSources.ts), how come this code is only supporting JSON-LD and N3?

And why hard-code the content type so literally (i.e. what if the actual HTTP content type header contained 5 RDF serialization media-types, and JSON-LD had the lowest 'q' value of all of them?):
```if (rdfSources[i].contentType === 'application/ld+json') {```

**Comment by michielbdejong** [comment]
The Solid spec only requires those two, but you're right about parsing the Content-Type header, that should be fixed.
