### ISSUE TITLE
'Magic' strings referring to vocab terms

### ISSUE THREAD

**Issue by pmcb55** [inrupt/wac-ldp#53]
This is just a placeholder for the moment really, but the use of 'http://www.w3.org/ns/ldp#contains' in (https://github.com/inrupt/wac-ldp/blob/master/src/lib/util/membersListAsResourceData.ts) illustrates the use of 'magic' strings in the code, which we should endeavor to replace with constants.

Constants (such as 'LDP.contains' in this case) would allow compile-time typo checking, provide code-completion for developers in their IDEs, and also provide JavaDoc documentation in IDE's for developers unfamiliar with the term. They are also simply more readable!

I'd suggest this be something Jarlath could look into when he formally joins, as the LIT framework (with which he is familiar) specifically supports all the above.

**Comment by michielbdejong** [comment]
Will include this in #54.
