### ISSUE TITLE
Consider representing LDP-RS as quad streams instead of strings

### ISSUE THREAD

**Issue by michielbdejong** [inrupt/wac-ldp#74]
During normal operation, an app will usually request the Turtle or JSON-LD document as it was stored, but there are also other requests that the server should support: converting to Turtle or to JSON-LD, filtering on a SPARQL query, paging, etc. In terms of code architecture it's cleaner to represent all LDP-RS as quad streams, and to serialize them into Turtle or into JSON-LD only on request.

So far, I discussed this with @dmitrizagidulin and @jaxoncreed and together we decided against this since in the bulk of cases an app will use the pod as just a dumb blob storage, and there it would be very silly to be converting to and from quad streams all the time; also, it would not preserve the literal text representation of the resource as it was written, so that's a bit ugly, and also this kind of system breaks down when you want to query triples from an RDFa document. So you would probably still need to do convert-on-read for RDFa docs which means we would have the worst of both worlds.

However, I realize that @RubenVerborgh did not get a chance yet to participate in that discussion, and neither did @kjetilk @pmcb55 and @justinwb so creating an issue about it here, for inclusion in #31.

**Comment by RubenVerborgh** [comment]
> and there it would be very silly to be converting to and from quad streams all the time;

That's why we make it a lazy stream.

Let's say the file on disk is Turtle. Then we create a quad stream from it (lazy, nothing happens), and then it comes to the serializer. Is the preferred content type Turtle? Just write the stream as it is, no transcoding needed. Is it JSON-LD or N-Triples? Parse and re-serialize.

**Comment by michielbdejong** [comment]
ok, agreed then! :) This is now handled by the content operations module from https://github.com/inrupt/wac-ldp#wac-ldp.

**Comment by michielbdejong** [comment]
Done with the QuadAndBlobStore, see #106
