### ISSUE TITLE
RDF graph caching

### ISSUE THREAD

**Issue by michielbdejong** [inrupt/wac-ldp#81]
We promised @RubenVerborgh that we would use a decorator pattern to implement caching. So I think the class to decorate would be RdfFetcher, and it can cache not just the documents retrieved, but the actual instantiated rdf graphs.

I can then also use that for #46, if I add a "persist" method to it. So then it's no longer strictly a decoration of the RdfFetcher. So then maybe I'll rename RdfFetcher to RdfFetcherAndUpdater, or just RdfLayer for short, and then I can decorate that to make it into RdfLayerWithCaching.

**Comment by michielbdejong** [comment]
yeah, that sounds right, I think that's what I'll do. will finish the v0.3 work and then work on this in v0.4.

**Comment by RubenVerborgh** [comment]
Is there a diagram with RdfFetcher?

**Comment by michielbdejong** [comment]
I'll include it in our Q2 presentation on Tuesday. It's basically just a caching decorator around an RdfLayer that provides access to local and remote RDF documents.

First parts of it are appearing here: https://github.com/inrupt/wac-ldp/blob/dev/src/lib/rdf/CachingRdfLayer.ts
